apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
  namespace: tfg
spec:
  ports:
  - protocol: TCP
    name: kafka-consumer
    targetPort: 9000
    port: 9000
  selector:
    app: kafka-consumer