apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: tfg
spec:
  ports:
  - port: 2181
    name: client
  - port: 2888
    name: server
  - port: 3888
    name: election-port
  clusterIP: None
  selector:
    app: zk