apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-configmap
  namespace: tfg
data:
  startKafka.sh: |-
    #!/bin/bash

    id=$(cat /etc/hostname | cut -d '-' -f 2)

    logDir="/var/lib/kafka/kafka-$id/logs"
    propertiesFile="/opt/bitnami/kafka/config/server.properties"

    # Limpiamos (en caso de que exista) y creamos el directorio en caso de que no exista el directorio logs
    rm -rf $logDir
    mkdir -p $logDir

    # Borramos y creamos la configuración en el fichero server.properties
    rm -f $propertiesFile
    touch $propertiesFile

    echo "broker.id=$id" >> $propertiesFile
    echo "listeners=PLAINTEXT://kafka-$id.kafka-hs.tfg.svc.cluster.local:9092" >> $propertiesFile
    echo "zookeeper.connect=zk-$id.zk-hs.tfg.svc.cluster.local:2181" >> $propertiesFile
    echo "num.network.threads=3" >> $propertiesFile
    echo "num.io.threads=8" >> $propertiesFile
    echo "socket.send.buffer.bytes=102400" >> $propertiesFile
    echo "socket.receive.buffer.bytes=102400" >> $propertiesFile
    echo "socket.request.max.bytes=104857600" >> $propertiesFile
    echo "log.dirs=$logDir" >> $propertiesFile
    echo "num.partitions=1" >> $propertiesFile
    echo "num.recovery.threads.per.data.dir=1" >> $propertiesFile
    echo "offsets.topic.replication.factor=3" >> $propertiesFile
    echo "transaction.state.log.replication.factor=1" >> $propertiesFile
    echo "transaction.state.log.min.isr=1" >> $propertiesFile
    echo "log.retention.hours=168" >> $propertiesFile
    echo "log.retention.check.interval.ms=300000" >> $propertiesFile
    echo "zookeeper.connection.timeout.ms=18000" >> $propertiesFile
    echo "group.initial.rebalance.delay.ms=0" >> $propertiesFile

    # Se ejecuta el fichero kafka-server-start.sh con la configuración que acabamos de crear
    exec kafka-server-start.sh /opt/bitnami/kafka/config/server.properties

